server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desactivar caché estricto para HTML, JS y JSON
    location ~* \.(?:html|js|json)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires -1;
    }

    # Caché únicamente para fuentes e imágenes estáticas
    location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|otf|ttf|svg)$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public";
    }
}
